/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guias;

import conexão.ConectaBanco;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonatan
 */
public class LaudosMedicos extends javax.swing.JInternalFrame {

    Connection con;
    PreparedStatement pst;

    /**
     * Creates new form LaudosMedicos
     */
    public LaudosMedicos() {
        initComponents();
        dtm = (DefaultTableModel) tabPacienteLaudos.getModel();
    }
    //Sempre necessario para manipular tabelas com registros criar uma default table nome
    // não esquecer de inicar as tabelas no construtro da classe.
    public DefaultTableModel dtm;

    public void log() throws SQLException {
        String CadtroPaciente;
        con = ConectaBanco.conecta("bdclinica");
        String sql = "Insert into log (acao,data,login_cod)"
                + "values ('Laudo Medico Consultas',current_timestamp,?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, Principal.lbCod.getText());
            pst.execute();
            pst.close();
//            JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!", "Cadastrar Pacientes", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Descrição do Erro! " + error.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbPreLaudos = new javax.swing.JComboBox();
        btnSalvarLaudo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnFecharLaudos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaLaudos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnBuscaPacienteLaudo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabPacienteLaudos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSintomasLaudo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeMedicoLaudos = new javax.swing.JTextField();
        lbCodConsulta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".::Laudos Medicos::.");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        cbPreLaudos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<selecione>", "Alta", "Tratamento médico", "Internado" }));
        cbPreLaudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPreLaudosActionPerformed(evt);
            }
        });

        btnSalvarLaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1411837995_icon-checkmark-16.png"))); // NOI18N
        btnSalvarLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLaudoActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1411839738_icon-compose-16.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1411783486_icon-loop-16.png"))); // NOI18N

        btnFecharLaudos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1411838523_icon-close-round-16.png"))); // NOI18N
        btnFecharLaudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharLaudosActionPerformed(evt);
            }
        });

        jLabel5.setText("Pre-Laudos");

        jLabel2.setText("Laudo Médico:");

        txtAreaLaudos.setBackground(new java.awt.Color(204, 255, 255));
        txtAreaLaudos.setColumns(20);
        txtAreaLaudos.setRows(5);
        jScrollPane2.setViewportView(txtAreaLaudos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes Para Serem Examinados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        btnBuscaPacienteLaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1411783471_icon-ios7-search-strong-16.png"))); // NOI18N
        btnBuscaPacienteLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPacienteLaudoActionPerformed(evt);
            }
        });

        tabPacienteLaudos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Horario", "Triagem", "Sintomas", "cod Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPacienteLaudos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPacienteLaudosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabPacienteLaudos);
        if (tabPacienteLaudos.getColumnModel().getColumnCount() > 0) {
            tabPacienteLaudos.getColumnModel().getColumn(0).setResizable(false);
            tabPacienteLaudos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabPacienteLaudos.getColumnModel().getColumn(1).setResizable(false);
            tabPacienteLaudos.getColumnModel().getColumn(1).setPreferredWidth(10);
            tabPacienteLaudos.getColumnModel().getColumn(2).setResizable(false);
            tabPacienteLaudos.getColumnModel().getColumn(2).setPreferredWidth(10);
            tabPacienteLaudos.getColumnModel().getColumn(3).setMinWidth(0);
            tabPacienteLaudos.getColumnModel().getColumn(3).setPreferredWidth(0);
            tabPacienteLaudos.getColumnModel().getColumn(3).setMaxWidth(0);
            tabPacienteLaudos.getColumnModel().getColumn(4).setMinWidth(0);
            tabPacienteLaudos.getColumnModel().getColumn(4).setPreferredWidth(0);
            tabPacienteLaudos.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        txtAreaSintomasLaudo.setBackground(new java.awt.Color(204, 255, 255));
        txtAreaSintomasLaudo.setColumns(20);
        txtAreaSintomasLaudo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAreaSintomasLaudo.setForeground(new java.awt.Color(0, 0, 153));
        txtAreaSintomasLaudo.setRows(5);
        jScrollPane1.setViewportView(txtAreaSintomasLaudo);

        jLabel1.setText("Médico/CRM:");

        jLabel6.setText("Sintomas:");

        txtNomeMedicoLaudos.setBackground(new java.awt.Color(204, 255, 255));
        txtNomeMedicoLaudos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNomeMedicoLaudos.setForeground(new java.awt.Color(0, 0, 153));
        txtNomeMedicoLaudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMedicoLaudosActionPerformed(evt);
            }
        });

        lbCodConsulta.setBackground(new java.awt.Color(255, 255, 255));
        lbCodConsulta.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbCodConsulta.setForeground(new java.awt.Color(255, 255, 255));
        lbCodConsulta.setText("codCliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lbCodConsulta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeMedicoLaudos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaPacienteLaudo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomeMedicoLaudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscaPacienteLaudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodConsulta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Historico de Altas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(btnSalvarLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharLaudos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPreLaudos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFecharLaudos, btnSalvarLaudo, jButton2, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbPreLaudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFecharLaudos)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(btnSalvarLaudo)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharLaudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharLaudosActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharLaudosActionPerformed

    private void btnBuscaPacienteLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPacienteLaudoActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_btnBuscaPacienteLaudoActionPerformed

    public void atualizaTabela() throws HeadlessException {
        dtm.setRowCount(0);
//        Connection con;
        try {
            con = ConectaBanco.conecta("bdclinica");
            String sql = "select p.nome, c.horario,c.tipo_consulta,c.sintomas,c.data_consulta, m.nome, c.idconsulta "
                    + "from paciente p , consulta c, medico m "
                    + "where c.medico_cod = m.cod "
                    + "and c.paciente_cod = p.cod "
                    + "and tipo_consulta<>'alta'"
                    + "and m.nome like ? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeMedicoLaudos.getText() + "%");

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Object Linha[] = {rs.getString("p.Nome"), //false, false};
                    rs.getString("c.horario"),
                    rs.getString("c.tipo_consulta"),
                    rs.getString("c.sintomas"),
                    rs.getString("c.idconsulta"), false, false};
                dtm.addRow(Linha);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro :" + e.getMessage());
        }
    }

    private void cbPreLaudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPreLaudosActionPerformed
        switch (cbPreLaudos.getSelectedIndex()) {
            case 0:

                break;
            case 1:
                txtAreaLaudos.setText("Alta –Paciente\n foi liberado da clínica após a consulta,não havendo necessidade\n"
                        + "de retornar na clínica.\n \nOBS MEDICAS:" + "");
                break;
            case 2:
                txtAreaLaudos.setText("Tratamento médico –\nPaciente foi liberado da clínica após a consulta havendo\n"
                        + "a necessidade de retornar na clínica.\n \nOBS MEDICAS:" + "");
                break;
            case 3:
                txtAreaLaudos.setText("Internado –\n Paciente não pode sair da clínica pois demanda um tratamento grave.\n \nOBS MEDICAS:" + "");
                break;
        }
    }//GEN-LAST:event_cbPreLaudosActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        dtm.setRowCount(0);
        ListaTabPalacienteLaudo();

    }//GEN-LAST:event_formInternalFrameOpened

    private void tabPacienteLaudosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPacienteLaudosMouseClicked
        int linha_selecionada = tabPacienteLaudos.getSelectedRow();
        tabPacienteLaudos.getValueAt(linha_selecionada, 3).toString();
        txtAreaSintomasLaudo.setText("" + tabPacienteLaudos.getValueAt(linha_selecionada, 3));
        tabPacienteLaudos.getValueAt(linha_selecionada, 4).toString();
        lbCodConsulta.setText("" + tabPacienteLaudos.getValueAt(linha_selecionada, 4));
    }//GEN-LAST:event_tabPacienteLaudosMouseClicked

    public void ListaTabPalacienteLaudo() throws HeadlessException {
        try {
            con = ConectaBanco.conecta("bdclinica");
            String sql = "select p.nome, c.horario,c.tipo_consulta,c.sintomas,c.data_consulta,m.nome,c.idconsulta "
                    + "from paciente p , consulta c, medico m "
                    + "where  c.medico_cod = m.cod "
                    + "and c.paciente_cod = p.cod "
                    + "and tipo_consulta<>'alta'"
                    + "and m.nome like ? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Principal.lbOperador.getText() + "%");

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Object Linha[] = {rs.getString("p.Nome"), //false, false};
                    rs.getString("c.horario"),
                    rs.getString("c.tipo_consulta"),
                    rs.getString("c.sintomas"),
                    rs.getString("c.idconsulta"), false, false};
                dtm.addRow(Linha);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro :" + e.getMessage());
        }
    }

    private void txtNomeMedicoLaudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMedicoLaudosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMedicoLaudosActionPerformed

    private void btnSalvarLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLaudoActionPerformed
        String sql = "update consulta set tipo_consulta=?,sintomas=? where idconsulta=?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, cbPreLaudos.getSelectedItem().toString());
            pst.setString(2, txtAreaLaudos.getText());
            pst.setString(3, lbCodConsulta.getText());
            //pst.executeUpdate();
            if (pst.executeUpdate() > 0) {
                log();
                JOptionPane.showMessageDialog(null, "Sucesso na Alteração!", "Alterar Pacientes", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao Alterar!", "Alterar Pacientes", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Descrição do Erro! " + error.getMessage());
        }
//        atualizaTabela();
        ListaTabPalacienteLaudo();
    }//GEN-LAST:event_btnSalvarLaudoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        funcoes.funcao.info_laudos();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaPacienteLaudo;
    private javax.swing.JButton btnFecharLaudos;
    private javax.swing.JButton btnSalvarLaudo;
    private javax.swing.JComboBox cbPreLaudos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lbCodConsulta;
    private javax.swing.JTable tabPacienteLaudos;
    private javax.swing.JTextArea txtAreaLaudos;
    private javax.swing.JTextArea txtAreaSintomasLaudo;
    public static javax.swing.JTextField txtNomeMedicoLaudos;
    // End of variables declaration//GEN-END:variables
}
